lab7/urls.py
from django.urls import path
from . import views

app_name = "lab7"
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('success', views.success, name='success'),
    path('mistakes', views.mistakes, name='mistakes'),
]

vulnerableapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.views.static import serve
from django.urls import re_path as url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('lab7.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

lab7/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username= models.CharField(max_length=100, null=True)
    password= models.CharField(max_length=100, null=True)

lab7/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
import os
from django.db import connection
from .models import User
import js2py

# Create your views here.
def index(request):
    if request.method == 'POST':
        del request.session['username']
        return render(request, 'index.html', {"username" : ""})
    else:
        if request.session.has_key('username'):
            username = request.session['username']
            return render(request,  'index.html', {"username" : username})
        else:
            return render(request, 'index.html', {"username" : ""})

def success(request):
    if request.session.has_key('username'):
        username = request.session['username']
    else:
        username=""
    return render(request,  'success.html', {"username" : ""})
    
def mistakes(request):
    if request.session.has_key('username'):
        username = request.session['username']
    else:
        username=""
    return render(request,  'mistakes.html', {"username" : ""})

def login(request):
    args = {}
    if request.method == 'POST':
        try:
            myusername = User.objects.filter(username=request.POST.get("user"))[0].username
        except:
            args = {}
            args['message'] = "Unknown Username!"
            return render(request, 'login.html',args)
        mypassword = User.objects.filter(username=request.POST.get("user"))[0].password
        if mypassword == request.POST.get("pass"):
            request.session['username'] = User.objects.filter(username=request.POST.get("user"))[0].username
            myusername = request.session['username']
            return render(request, 'success.html', {"username" : myusername})
        else:
            args = {}
            args['message'] = "Wrong Password!"
            return render(request, 'login.html',args)
    else:
        return render(request, 'login.html', {"username" : ""})

templates/index.html

<style>
html {
  background-color: #565656
}

body {
  font-size: 18px;
  font-family: Verdana, Geneva, sans-serif;
  line-height: 1.5;
  color: white;
}

.navbar {
  height: 50px;
  position: fixed;
  width: 100%;
  background-image: linear-gradient(#081829 , #6B798C);
  z-index: 100;
}

.wrapper, .main-wrapper {
  width: 1200px;
  margin: 0 auto;
  padding-left: 30px;
  padding-right: 30px;
  box-sizing: border-box;

}

.navbar .wrapper {
  background-color: rgba(255,255,255,0.1);
}

.main-wrapper {
  font-size: 1.1em;
  padding-top: 80px;
  padding-bottom: 80px;
  padding-right: 80px;
  padding-left: 80px;
  background-image:  url("https://i.imgur.com/VGv0QE1.jpg");
  background-size: cover;
  position: relative;
  z-index: 1;
}

.logo {
  display: inline-block;
}

.logo a {
  line-height: 50px;
  font-size: 1.75em;
  font-weight: bold;
  text-decoration: none;
  color: gold;
}

.mainmenu {
  float: right;
  list-style: none;
  padding: 0;
  margin: 0;
  font-size: 0;
}

.mainmenu li {
  display: inline;
}

button{
  line-height: 50px;
  text-decoration: none;
  color: black;
  font-size: 18px;
  font-weight: bold;
  padding: 0;
  border: none;
  background: none;
}

button:hover{
  color: #EDA444;
}

.mainmenu li a{
  line-height: 50px;
  text-decoration: none;
  color: black;
  font-size: 18px;
  font-weight: bold;
}

.mainmenu li a:hover {
  color: #EDA444;
}

.mainmenu li:not(:last-child) {
  margin-right: 30px;
}

img.myface {
  float: left;
  border-radius: 10px;
  margin-right: 30px;
}

.section:before {
  content: " ";
  display: block;
  position: absolute;
  width: 100%;
  height: 100%;
  background-color: rgba(11,66,131,0.5);
  left: 0px;
  top: 0px;
  z-index: -1;
  border-radius: 10px;
}



.section {
  z-index: 100;
  position: relative;
  padding: 30px;
  vertical-align: top;
  
}

.section h1 {
  margin: 0;
}

.section p {
  position: relative;
}

.section a{
  color: gold;
  font-weight: bold;
  text-decoration: none;
}

.section a:hover {
  color: red;
}

img.ninetysdesk {
  border-radius: 10px;
  margin-left: 30px;
  float: right;
}

img.webtech {
  border-radius: 10px;
  margin-right: 30px;
  float: left;
}

img {
  box-shadow: 2px 2px 3px 0px rgba(0,0,0,0.8);
  background-color: white;
}

td {
  padding: 10px;
  vertical-align: bottom;
}

table {
  float: left;
}

.clearfix {
  clear: both;
  height: 0px;
}
</style>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<nav class="navbar">
    <div class="wrapper">
        <div class="logo"><a href="{% url 'lab7:index' %}">Lab 7</a></div>
        <ul class="mainmenu">
          <form method="post">
            {% csrf_token %}
          {% if username != "" %}
          <li><a href="">Welcome {{username}}</a></li>
          <button type="submit">Log Out</button>
          {% endif %}
          </form>
          {% if username == "" %}
          <li><a href="{% url 'lab7:login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    
    <div class="main-wrapper">
     <div class="section about-section">
       <h1>Vulnerable Web Application</h1>
       <p>This application contains vulnerabilities. Try to find them.</p>
     </div>
    </div>
    
</html>

templates/login.html

<style>
  html {
    background-color: #565656
  }
  
  body {
    font-size: 18px;
    font-family: Verdana, Geneva, sans-serif;
    line-height: 1.5;
    color: white;
  }
  
  .navbar {
    height: 50px;
    position: fixed;
    width: 100%;
    background-image: linear-gradient(#081829 , #6B798C);
    z-index: 100;
  }
  
  .wrapper, .main-wrapper {
    width: 1200px;
    margin: 0 auto;
    padding-left: 30px;
    padding-right: 30px;
    box-sizing: border-box;
  
  }
  
  .navbar .wrapper {
    background-color: rgba(255,255,255,0.1);
  }
  
  .main-wrapper {
    font-size: 1.1em;
    padding-top: 80px;
    padding-bottom: 80px;
    padding-right: 80px;
    padding-left: 80px;
    background-image:  url("https://i.imgur.com/VGv0QE1.jpg");
    background-size: cover;
    position: relative;
    z-index: 1;
  }
  
  .logo {
    display: inline-block;
  }
  
  .logo a {
    line-height: 50px;
    font-size: 1.75em;
    font-weight: bold;
    text-decoration: none;
    color: gold;
  }
  
  .mainmenu {
    float: right;
    list-style: none;
    padding: 0;
    margin: 0;
    font-size: 0;
  }
  
  .mainmenu li {
    display: inline;
  }
  
  button{
    line-height: 50px;
    text-decoration: none;
    color: black;
    font-size: 18px;
    font-weight: bold;
    padding: 0;
    border: none;
    background: none;
  }
  
  button:hover{
    color: #EDA444;
  }
  
  .mainmenu li a{
    line-height: 50px;
    text-decoration: none;
    color: black;
    font-size: 18px;
    font-weight: bold;
  }
  
  .mainmenu li a:hover {
    color: #EDA444;
  }
  
  .mainmenu li:not(:last-child) {
    margin-right: 30px;
  }
  
  img.myface {
    float: left;
    border-radius: 10px;
    margin-right: 30px;
  }
  
  .section:before {
    content: " ";
    display: block;
    position: absolute;
    width: 100%;
    height: 100%;
    background-color: rgba(11,66,131,0.5);
    left: 0px;
    top: 0px;
    z-index: -1;
    border-radius: 10px;
  }
  
  
  
  .section {
    z-index: 100;
    position: relative;
    padding: 30px;
    vertical-align: top;
    
  }
  
  .section h1 {
    margin: 0;
  }
  
  .section p {
    position: relative;
  }
  
  .section a{
    color: gold;
    font-weight: bold;
    text-decoration: none;
  }
  
  .section a:hover {
    color: red;
  }
  
  img.ninetysdesk {
    border-radius: 10px;
    margin-left: 30px;
    float: right;
  }
  
  img.webtech {
    border-radius: 10px;
    margin-right: 30px;
    float: left;
  }
  
  img {
    box-shadow: 2px 2px 3px 0px rgba(0,0,0,0.8);
    background-color: white;
  }
  
  td {
    padding: 10px;
    vertical-align: bottom;
  }
  
  table {
    float: left;
  }
  
  .clearfix {
    clear: both;
    height: 0px;
  }
  </style>
  <html>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <nav class="navbar">
    <div class="wrapper">
        <div class="logo"><a href="{% url 'lab7:index' %}">Lab 7</a></div>
        <ul class="mainmenu">
          <form method="post">
            {% csrf_token %}
          {% if username != "" %}
          <li><a href="">Welcome {{username}}</a></li>
          <button type="submit">Log Out</button>
          {% endif %}
          </form>
          {% if username == "" %}
          <li><a href="{% url 'lab7:login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
      {% if message != None %}
      <script>alert("{{message}}")</script>
      {% endif %}
      <div class="main-wrapper">
       <div class="section about-section">
        <h1>Enter your credentials!</h1>
        <div class="login-form">
          <form method="post">
            {% csrf_token %}
            <!-- username:admin,password:admin -->
            <input type="text" name="user" placeholder="Username"/>
            <input type="password" name="pass" placeholder="Password"/>
            <button type="submit">Submit</button>
          </form>
        </div>
       </div>
      </div>
  </html>

templates/mistakes.html

<style>
html {
  background-color: #565656
}

body {
  font-size: 18px;
  font-family: Verdana, Geneva, sans-serif;
  line-height: 1.5;
  color: white;
}

.navbar {
  height: 50px;
  position: fixed;
  width: 100%;
  background-image: linear-gradient(#081829 , #6B798C);
  z-index: 100;
}

.wrapper, .main-wrapper {
  width: 1200px;
  margin: 0 auto;
  padding-left: 30px;
  padding-right: 30px;
  box-sizing: border-box;

}

.navbar .wrapper {
  background-color: rgba(255,255,255,0.1);
}

.main-wrapper {
  font-size: 1.1em;
  padding-top: 80px;
  padding-bottom: 80px;
  padding-right: 80px;
  padding-left: 80px;
  background-image:  url("https://i.imgur.com/VGv0QE1.jpg");
  background-size: cover;
  position: relative;
  z-index: 1;
}

.logo {
  display: inline-block;
}

.logo a {
  line-height: 50px;
  font-size: 1.75em;
  font-weight: bold;
  text-decoration: none;
  color: gold;
}

.mainmenu {
  float: right;
  list-style: none;
  padding: 0;
  margin: 0;
  font-size: 0;
}

.mainmenu li {
  display: inline;
}

button{
  line-height: 50px;
  text-decoration: none;
  color: black;
  font-size: 18px;
  font-weight: bold;
  padding: 0;
  border: none;
  background: none;
}

button:hover{
  color: #EDA444;
}

.mainmenu li a{
  line-height: 50px;
  text-decoration: none;
  color: black;
  font-size: 18px;
  font-weight: bold;
}

.mainmenu li a:hover {
  color: #EDA444;
}

.mainmenu li:not(:last-child) {
  margin-right: 30px;
}

img.myface {
  float: left;
  border-radius: 10px;
  margin-right: 30px;
}

.section:before {
  content: " ";
  display: block;
  position: absolute;
  width: 100%;
  height: 100%;
  background-color: rgba(11,66,131,0.5);
  left: 0px;
  top: 0px;
  z-index: -1;
  border-radius: 10px;
}



.section {
  z-index: 100;
  position: relative;
  padding: 30px;
  vertical-align: top;
  
}

.section h1 {
  margin: 0;
}

.section p {
  position: relative;
}

.section a{
  color: gold;
  font-weight: bold;
  text-decoration: none;
}

.section a:hover {
  color: red;
}

img.ninetysdesk {
  border-radius: 10px;
  margin-left: 30px;
  float: right;
}

img.webtech {
  border-radius: 10px;
  margin-right: 30px;
  float: left;
}

img {
  box-shadow: 2px 2px 3px 0px rgba(0,0,0,0.8);
  background-color: white;
}

td {
  padding: 10px;
  vertical-align: bottom;
}

table {
  float: left;
}

.clearfix {
  clear: both;
  height: 0px;
}
</style>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<nav class="navbar">
  <div class="wrapper">
      <div class="logo"><a href="{% url 'lab7:index' %}">Lab 7</a></div>
      <ul class="mainmenu">
        <form method="post">
          {% csrf_token %}
        {% if username != "" %}
        <li><a href="">Welcome {{username}}</a></li>
        <button type="submit">Log Out</button>
        {% endif %}
        </form>
        {% if username == "" %}
        <li><a href="{% url 'lab7:login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
    <div class="main-wrapper">
     <div class="section about-section">
      <h1>Mistakes...</h1>
      <p>Mistakes could occur when you forget to restrict sensitive pages to users.</p>
     </div>
    </div>
    
</html>

templates/success.html

<style>
  html {
    background-color: #565656
  }
  
  body {
    font-size: 18px;
    font-family: Verdana, Geneva, sans-serif;
    line-height: 1.5;
    color: white;
  }
  
  .navbar {
    height: 50px;
    position: fixed;
    width: 100%;
    background-image: linear-gradient(#081829 , #6B798C);
    z-index: 100;
  }
  
  .wrapper, .main-wrapper {
    width: 1200px;
    margin: 0 auto;
    padding-left: 30px;
    padding-right: 30px;
    box-sizing: border-box;
  
  }
  
  .navbar .wrapper {
    background-color: rgba(255,255,255,0.1);
  }
  
  .main-wrapper {
    font-size: 1.1em;
    padding-top: 80px;
    padding-bottom: 80px;
    padding-right: 80px;
    padding-left: 80px;
    background-image:  url("https://i.imgur.com/VGv0QE1.jpg");
    background-size: cover;
    position: relative;
    z-index: 1;
  }
  
  .logo {
    display: inline-block;
  }
  
  .logo a {
    line-height: 50px;
    font-size: 1.75em;
    font-weight: bold;
    text-decoration: none;
    color: gold;
  }
  
  .mainmenu {
    float: right;
    list-style: none;
    padding: 0;
    margin: 0;
    font-size: 0;
  }
  
  .mainmenu li {
    display: inline;
  }
  
  button{
    line-height: 50px;
    text-decoration: none;
    color: black;
    font-size: 18px;
    font-weight: bold;
    padding: 0;
    border: none;
    background: none;
  }
  
  button:hover{
    color: #EDA444;
  }
  
  .mainmenu li a{
    line-height: 50px;
    text-decoration: none;
    color: black;
    font-size: 18px;
    font-weight: bold;
  }
  
  .mainmenu li a:hover {
    color: #EDA444;
  }
  
  .mainmenu li:not(:last-child) {
    margin-right: 30px;
  }
  
  img.myface {
    float: left;
    border-radius: 10px;
    margin-right: 30px;
  }
  
  .section:before {
    content: " ";
    display: block;
    position: absolute;
    width: 100%;
    height: 100%;
    background-color: rgba(11,66,131,0.5);
    left: 0px;
    top: 0px;
    z-index: -1;
    border-radius: 10px;
  }
  
  
  
  .section {
    z-index: 100;
    position: relative;
    padding: 30px;
    vertical-align: top;
    
  }
  
  .section h1 {
    margin: 0;
  }
  
  .section p {
    position: relative;
  }
  
  .section a{
    color: gold;
    font-weight: bold;
    text-decoration: none;
  }
  
  .section a:hover {
    color: red;
  }
  
  img.ninetysdesk {
    border-radius: 10px;
    margin-left: 30px;
    float: right;
  }
  
  img.webtech {
    border-radius: 10px;
    margin-right: 30px;
    float: left;
  }
  
  img {
    box-shadow: 2px 2px 3px 0px rgba(0,0,0,0.8);
    background-color: white;
  }
  
  td {
    padding: 10px;
    vertical-align: bottom;
  }
  
  table {
    float: left;
  }
  
  .clearfix {
    clear: both;
    height: 0px;
  }
</style>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<nav class="navbar">
  <div class="wrapper">
      <div class="logo"><a href="{% url 'lab7:index' %}">Lab 7</a></div>
      <ul class="mainmenu">
        <form method="post">
          {% csrf_token %}
        {% if username != "" %}
        <li><a href="">Welcome {{username}}</a></li>
        <button type="submit">Log Out</button>
        {% endif %}
        </form>
        {% if username == "" %}
        <li><a href="{% url 'lab7:login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
    
    <div class="main-wrapper">
     <div class="section about-section">
      <h1>Success!</h1>
      <p>You've determined the secret password.</p>
     </div>
    </div>
</html>